language: python
sudo: false
cache: bundler

python:
  - pypy

# addons:
#   apt:
#     sources:
#       - llvm-toolchain-precise-3.7
#     packages:
#       - libarchive-dev
#       - clang-3.7
addons:
  apt:
    packages:
      - libarchive-dev

install:
  - pip install cffi
  - pip install pytest

script:
  - make tests
